import type { Locale } from './vi'

export const en: Locale = {
  languageName: 'English',
  header: { about: 'About us', services: 'Services', pricing: 'Pricing', trainers: 'Trainers', reviews: 'Reviews', trial: 'Book a free trial', language: 'Tiếng Việt', phoneLabel: 'Call VIO Fitness', menu: 'Open menu', close: 'Close menu', mobileNavigation: 'Mobile navigation' },
  hero: { alt: 'VIO Fitness training space in Da Nang', titleBefore: 'An international-standard gym', titleAccent: 'in the heart', titleAfter: 'of Da Nang', description: 'Personalized 1-on-1 training with professional coaches, Panatta and Hammer Strength equipment, and a focused environment for progress.', primary: 'Book a free trial', secondary: 'Explore facilities', google: 'Google', facebook: 'Facebook' },
  trust: { panatta: 'PANATTA SPORT', hammer: 'HAMMER STRENGTH', premium: 'PREMIUM GYM', international: 'INTERNATIONAL STANDARD', personal: 'PERSONAL TRAINING', sauna: 'SAUNA & RECOVERY', recovery: 'RECOVERY ZONE', boxing: 'BOXING AREA', openDays: 'OPEN 7 DAYS A WEEK' },
  reviews: { label: 'Reviews', heading: 'What members say about VIO.', button: 'See all reviews on Google Maps', verified: 'Rating snapshot last verified from information supplied by the owner.' },
  positioning: { eyebrow: 'About VIO', title: 'Not built for crowds. Built for quality.', body: 'Three floors of space, carefully selected equipment, and a team ready to support your next step.', cta: 'Find your best plan' },
  services: { eyebrow: 'More than a gym.', title: 'A place to belong.', body: 'We are not only a gym. We are a space built for every journey — whether you are just starting or pushing past your limits. Progress matters more than perfection.', equipment: '100% new equipment', floors: '3 floors of space', personal: '1-on-1 personal training', cta: 'Book a visit', items: { equipment: { tag: '01 · EQUIPMENT', title: 'Premium equipment', description: 'Panatta and Hammer Strength equipment arranged by muscle group to help you train with confidence and consistency.', detail: 'The equipment is checked and maintained regularly by the technical team.' }, functional: { tag: '02 · FLOOR 2', title: 'Functional zone', description: 'A dedicated boxing and functional-training space with room to move through every session.', detail: 'Suitable for beginners, regular members, and athletes.' }, recovery: { tag: '03 · CARE', title: 'Recovery and therapy', description: 'A dedicated area for personal training and recovery support when your body needs a more considered approach.', detail: 'Ask the VIO team about the current services available.' }, sauna: { tag: '04 · RELAX', title: 'Dry sauna', description: 'A private, clean sauna space to help you relax and recover after training.', detail: 'Ask the team about current access and availability.' }, nutrition: { tag: '05 · NUTRITION', title: 'Refuel', description: 'Protein shakes, fresh smoothies, and healthier snacks are available at the gym.', detail: 'Ask VIO about the current menu and service hours.' } } },
  trainers: { eyebrow: 'Here to support you', title: 'Our trainer profiles are being updated', body: 'VIO is completing each trainer profile so we can present verified specialties and coaching styles. Book a trial to speak with the team directly.', cta: 'Book a consultation', verified: 'Verified trainers' },
  stories: { eyebrow: 'VIO community', title: 'Real people. Real journeys.', body: 'Watch member stories supplied by VIO. Every story is shared with consent from the person featured.', video: 'Member video', watch: 'Watch story' },
  pricing: { eyebrow: 'VIO Fitness plans', title: 'Choose how you train', subtitle: 'From one session to a longer commitment. Every plan leads to the same simple enquiry form before you decide.', popular: 'Most popular', paymentTitle: 'Flexible payment', paymentIntro: 'Choose a method that suits you and pay directly with the VIO team.', paymentMethods: 'Cash · Card · Bank transfer', paymentCash: 'Cash', paymentCard: 'Card', paymentTransfer: 'Bank transfer', choose: 'Choose this plan', trial: 'Book a free trial', periodDay: '/ DAY', periodDays: '/ 3 DAYS', periodWeek: '/ WEEK', periodMonth: '/ MONTH', periodYear: '/ 12 MONTHS', plans: { dayPass: { prefix: 'FLEXIBLE', features: ['Unlimited gym access', 'Air-conditioned training space'] }, shortTerm: { prefix: 'VISITOR', features: ['Unlimited gym access', 'Air-conditioned training space'] }, weeklyPass: { prefix: 'TRAVELER', features: ['2 weeks: 1.25M VND / $50', 'Unlimited gym access', 'Air-conditioned training space'] }, membership: { prefix: 'COMMITTED', features: ['2 months: 2.9M VND / $116', '3 months: 3.9M VND / $156', '6 months: 6.6M VND / $264', 'Unlimited gym access'] }, longTerm: { prefix: 'LIFESTYLE', features: ['Unlimited gym access', 'Air-conditioned training space'] } } },
  map: { title: 'VIO Fitness', directions: 'Get directions', frameTitle: 'VIO Fitness location map' },
  footer: { quickLinks: 'Quick links', contact: 'Contact information', hours: 'Opening hours', hoursDay: 'Monday – Sunday', trialTitle: 'Book a free trial', trialBody: 'Your first trial is free, including an InBody scan and an introduction to the equipment with a coach.', zaloButton: 'Message on Zalo', whatsappButton: 'Book via WhatsApp', rights: 'All rights reserved', phoneLabel: 'Hotline', emailLabel: 'Email' },
  trial: { eyebrow: 'Start simply', title: 'Book your free trial session', body: 'Share 3 quick details. VIO will open the right chat channel for your request.', name: 'Your name', goal: 'Training goal', time: 'Preferred time', choose: 'Choose a goal', timePlaceholder: 'Example: 17:00–19:00', zalo: 'Book via WhatsApp', instagram: 'Message on Instagram', call: 'Call the gym', copied: 'Message copied. Paste it into the Zalo/Instagram chat!', copyFailed: 'The message could not be copied. Please enter the 3 details again in the chat window.', required: 'Please enter your name, goal and preferred time.', offer: 'Free trial session + free InBody scan', close: 'Close form' },
  goals: { muscle: 'Build muscle', weightLoss: 'Lose weight', beginner: 'Getting started', personalTraining: '1-on-1 personal training', traveller: 'Visitor / traveller' },
}
